# Generated by Django 2.0.2 on 2018-04-02 13:01

from django.db import migrations, models
import forum.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20180401_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to=forum.models.upload),
        ),
    ]
