# Generated by Django 2.0.2 on 2018-04-03 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_post_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='like',
        ),
    ]
