# Generated by Django 2.0.2 on 2018-04-04 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_auto_20180404_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='body',
            new_name='ask_question',
        ),
    ]
