# Generated by Django 2.0.2 on 2018-07-17 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_auto_20180404_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='text',
            new_name='body',
        ),
    ]
