# Generated by Django 2.0.2 on 2018-03-30 23:12

from django.db import migrations, models
import django.db.models.deletion
import efarm.models


class Migration(migrations.Migration):

    dependencies = [
        ('efarm', '0002_auto_20180219_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='efarm.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=efarm.models.upload_to),
        ),
    ]
